debug code

diff --git a/.github/workflows/code_challenge.yml b/.github/workflows/code_challenge.yml
--- a/.github/workflows/code_challenge.yml
+++ b/.github/workflows/code_challenge.yml
@@ -27,47 +27,51 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Setup Terraform with specified version on the runner
-        uses: hashicorp/setup-terraform@v3
+      # - name: Setup Terraform with specified version on the runner
+      #   uses: hashicorp/setup-terraform@v3
+      #   with:
+      #     terraform_version: "1.9.3"
+
+      # - name: Configure Terraform variables
+      #   id: key_vars
+      #   run: echo "public_key = \"$PUBLIC_KEY\"" > terraform.tfvars
+
+      # - name: Terraform init
+      #   id: init
+      #   run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+
+      # - name: Terraform format
+      #   id: fmt
+      #   run: terraform fmt -check
+
+      # - name: Terraform validate
+      #   id: validate
+      #   run: terraform validate
+
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -no-color -input=false -out planfile
+      #   continue-on-error: true
+
+      # - name: Terraform plan status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   id: apply
+      #   run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+      - name: Retrieve instance public IP
+        id: instance_ip
+        run: |
+          # echo "::set-output name=instance_ip::$(terraform output instance_public_ip)"
+          echo "::set-output name=instance_ip::$(pwd)"
+          echo "$INSTANCE_IP" > instance_ip.txt
+
+      - name: Store instance IP as artifact
+        uses: actions/upload-artifact@v4
         with:
-          terraform_version: "1.9.3"
-
-      - name: Configure Terraform variables
-        id: key_vars
-        run: echo "public_key = \"$PUBLIC_KEY\"" > terraform.tfvars
-
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
-
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt -check
-
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
-
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
-
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
-
-      - name: Update instance IP secret
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            github.actions.setSecret({
-              name: 'INSTANCE_PUBLIC_IP',
-              value: $(terraform output instance_ip)
-            })
-
+          name: instance_ip.txt
+          path: instance_ip.txt
+        
+        
