Test artifact from other job

diff --git a/.github/workflows/code_challenge.yml b/.github/workflows/code_challenge.yml
--- a/.github/workflows/code_challenge.yml
+++ b/.github/workflows/code_challenge.yml
@@ -15,61 +15,73 @@ env:
   PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
 
 jobs:
-  terraform:
-    name: "Apply terraform code changes"
+  # terraform:
+  #   name: "Apply terraform code changes"
+  #   runs-on: ubuntu-latest
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: ./terraform
+
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
+
+  #     - name: Setup Terraform with specified version on the runner
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         terraform_version: "1.9.3"
+  #     - name: Configure Terraform variables
+  #       id: key_vars
+  #       run: echo "public_key = \"$PUBLIC_KEY\"" > terraform.tfvars
+
+  #     - name: Terraform init
+  #       id: init
+  #       run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+
+  #     - name: Terraform format
+  #       id: fmt
+  #       run: terraform fmt -check
+
+  #     - name: Terraform validate
+  #       id: validate
+  #       run: terraform validate
+
+  #     - name: Terraform plan
+  #       id: plan
+  #       run: terraform plan -no-color -input=false -out planfile
+  #       continue-on-error: true
+
+  #     - name: Terraform plan status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
+
+  #     - name: Terraform Apply
+  #       id: apply
+  #       run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+  #     - name: Retrieve instance public IP and store in file
+  #       id: instance_ip
+  #       run: |
+  #         echo "$(terraform output instance_ip)" > instance_ip.txt
+
+  #     - name: upload ip file as artifact
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: instance_ip.txt
+  #         path: ./terraform/instance_ip.txt
+
+  ansible:
+    # needs: terraform
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terraform
 
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
-      - name: Setup Terraform with specified version on the runner
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: "1.9.3"
-      - name: Configure Terraform variables
-        id: key_vars
-        run: echo "public_key = \"$PUBLIC_KEY\"" > terraform.tfvars
-
-      - name: Terraform init
-        id: init
-        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
-
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt -check
-
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
-
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -no-color -input=false -out planfile
-        continue-on-error: true
-
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
-      - name: Terraform Apply
-        id: apply
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
-
-      - name: Retrieve instance public IP and store in file
-        id: instance_ip
+      # - name: Checkout code
+        # uses: actions/checkout@v4
+      
+      - name: Download instace IP artifact
+        id: get_artifact
         run: |
-          echo "$(terraform output instance_ip)" > instance_ip.txt
-
-      - name: upload ip file as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: instance_ip.txt
-          path: ./terraform/instance_ip.txt
-
-        
+          INSTANCE_IP=$(cat instance_ip.txt)
+          echo "EC2 instance Public IP: $INSTANCE_IP"
         
